export const sideLetterReps = {
    'rep1': `Immediately after the closing of Investor’s investment in the Company (the “Investment”), one or both of the following will be true (i) the Company will not be, or own an interest in, a “Controlled Foreign Corporation” (“CFC”) as defined in the U.S. Internal Revenue Code of 1986, as amended (or any successor thereto) (the “Code”) or (ii) to the knowledge of the Company, Investor will not directly, indirectly or constructively own 10% or more of the total value or voting power of all shares of any CFC as a result of its investment into the Company (a significant “U.S. Shareholder” as defined in the Code). 
If following the Investment (i) the Company becomes a CFC when it was not a CFC immediately following the Investment, (ii) the Company acquires an interest in a CFC when it did not own any interest in a CFC immediately following the investment , (iii) Investor becomes a significant U.S. Shareholder in a CFC as a result of its investment into the company when it was not a U.S. Shareholder immediately following the Investment , or (iv) Investor communicates to Company in writing a reasonable basis for believing Company has become a CFC when it wasn’t a CFC immediately following the Investment, Company agrees to provide to Investor no later than 60 days following the end of each taxable year: 
A report from the Company’s tax advisors detailing whether any portion of the Company’s income is “subpart F income” (as defined in Section 952 of the Code) (“Subpart F Income”) and a report regarding the Company’s status as a CFC and/or ownership of interests in any CFC; and
The Company’s capitalization table as of the end of the last day of each taxable year, as well as access to such other Company information as may be necessary for the Investor to determine the Company’s status as a CFC and to determine whether the Investor or any of Investor’s Partners is required to report its pro rata portion of the Company’s Subpart F Income on its United States federal income tax return, or to allow the Investor or the Investor’s Partners to otherwise comply with applicable United States federal income tax laws. The term “Investor’s Partners” shall mean each of the Investor’s partners and any direct or indirect equity owners of such partners. The “Company” shall mean the Company and any of its subsidiaries.
Upon (i) a liquidity event whereby the Investor has liquidated all or part of its investment in the Company (ii) a tax audit of an Investor Partner in which Company’s status as a CFC is in question, Company agrees to provide Investor with written confirmation regarding Company’s status as a non-CFC for each year in which Investor held its investment in the Company.
`,
    'rep2': `The Company has never been, and, to the best of its knowledge, will not be with respect to its taxable year during which Investor makes its investment a “passive foreign investment company” within the meaning of Section 1297 of the Code (a “PFIC”). 
The company does not own, and to the best of its knowledge, will not own with respect to its taxable year during which investor makes its investment, an interest in a PFIC.
The Company shall use its commercially reasonable efforts to avoid being a PFIC or acquiring an interest in a company that is or may become a PFIC
If at any time following Investor’s investment, the Company becomes a PFIC, acquires an interest in a PFIC, or owns an interest in a company that becomes a PFIC, or if Investor communicates to Company in writing a reasonable basis for believing Company has become a PFIC, Company agrees to provide to Investor no later than 60 days following the end of each such taxable year):
Annual financial information to Investor for the Company, or any PFIC the Company is invested in, in the form provided in the attached PFIC Exhibit attached hereto (or in such other form as may be required to reflect changes in applicable law).
Access to such other Company information, or information for any PFIC the Company is invested in, as may be required for purposes of allowing the Investor to make a “Qualified Electing Fund” election pursuant to Section 1295 of the Code or “Protective Statement” filed by Investor pursuant to Treasury Regulations.
Upon (i) a liquidity event whereby the Investor has liquidated all or part of its investment in the Company (ii) a bona fide audit of Investor or one or more of Investor’s Partners in which Company’s status as a PFIC is in question, Company agrees to provide Investor with written confirmation regarding Company’s status as a non-PFIC, as well as written confirmation regarding the status of any Company investments as non-PFIC, for each year in which Investor held its investment in the Company.  
`,
    'rep3': `The Company shall take such actions, including making an election to be treated as a corporation or refraining from making an election to be treated as a partnership, as may be required to ensure that at all times the Company is classified as a corporation for United States federal income tax purposes.`,
    'rep4': `The Company shall take such actions, including making an election to be treated as a partnership or refraining from making an election to be treated as a corporation, as may be required to ensure that at all times the Company is classified as a partnership for U.S. federal income tax purposes, unless such change is necessary to avoid being deemed engaged in a United States trade or business`,
    'rep5': `As soon as practicable, but in any event within sixty (60) days after the end of each fiscal year of the Company, the Company shall deliver a schedule K-1 for such fiscal year and any additional information reasonably requested by the Investor in order to assist the Investor or any person who is a direct or indirect beneficial owner of the Investor with the preparation of its United States federal income tax returns, complying with reporting obligations under the United States Internal Revenue Code of 1986, as amended (the “Code”) (including, without limitation, pursuant to Sections 6038, 6038B, 6038D or 6046A of the Code and the rules and Treasury Regulations promulgated thereunder) and other obligations under the Code, or obtaining any benefit pursuant to the Code.`,
    'rep6': `The Company represents that it is not now and will not in the future become engaged in any active trade or business or hold equity interests in any operating companies that would cause the Company to allocate to the Investor (i) “Effectively Connected Taxable Income” as defined in Section 1446 of the Internal Revenue Code (or any successor thereto) or (ii) “Unrelated Business Tax Income” as defined in Section 512(a) of the Internal Revenue Code (or any successor thereto).`,
    'rep7': `The Investor agrees that in no case shall it take any action to enforce the rights provided for in this letter if such action shall cause material hardship to the Company. `,
    'rep8': `To the extent that Investor is allocated taxable income from Company in any fiscal year as a result of being a partner in the Company for US tax purposes, the Company shall make a distribution to Investor within forty-five (45) days of the end of the fiscal year during which Investor is allocated such income (a “Tax Distribution”). The amount of such Tax Distribution shall be equal to or greater than the highest combined U.S. federal and state tax rates applicable to each type of income allocated multiplied by the income allocated.`,
    'rep9': `Company agrees to take reasonable steps to record and/or transfer ownership of the Investor’s interest in the Company to an entity organized by Investor to hold the Investor’s interest in Company as a corporation for United States tax purposes (the “Investment Blocker”). If the Investment is held by the Investment Blocker and the Company converts into a “C” Corporation for United states tax purposes following the Investment, Company agrees to take commercially reasonable steps to allow the Investment Blocker to merge with and into such “C” Corporation to avoid causing the Investment to be subject to a second level of United States corporate tax at the Investment Blocker level.`,
    'rep10': `The Company agrees to take all necessary actions to be treated as a “C” Corporation for United States tax purposes prior to any event that would cause the Investor to be treated as an “equity holder” of the Company for United States tax purposes.`,
    'rep11': `Company shall provide written notice to Investor at least ten (10) days prior to any conversion of the Investment into equity securities of the Company.`,
    'rep12': `The Company represents that it has been organized as a “holding company” for the sole purpose of owning and holding interests in one or more affiliated operating corporations (or owning and holding interests in other holding companies that in turn solely own and hold interests in one or more affiliated operating corporations). The Company represents that it has or will take all required actions to ensure that it be treated as a partnership for US tax purposes.`,
    'rep13': `Company agrees to make standard representations regarding Controlled Foreign Corporation (“CFC”) and Passive Foreign Investment Company (“PFIC”) for US tax compliance purposes in the attached Exhibit, no later than the earlier of (i) immediately prior to the closing of the next equity financing that triggers the conversion of Investor’s investment into an equity interest in the company; and (ii) to the extent the investment instrument contains a maturity date, the maturity date. Company shall provide written notice to Investor at least five (5) days prior to the Investor receiving an interest in the Company characterized as equity for US tax purposes. The Company’s failure to perform the obligations hereunder shall constitute a material default under the terms of the investment.`
}

